[project]
name = 'Decentralized-Specialized-Medical-Device-Development'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.design-documentation]
path = 'contracts/design-documentation.clar'
clarity_version = 2
epoch = 2.5

[contracts.inventor-verification]
path = 'contracts/inventor-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.regulatory-submission]
path = 'contracts/regulatory-submission.clar'
clarity_version = 2
epoch = 2.5

[contracts.testing-verification]
path = 'contracts/testing-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
